version: "3.5"
services:
  db:
    image: mariadb:10.3
    ports:
      - "5000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tj3gms4!
      - MYSQL_DATABASE=todoList
      - TZ=Asia/Seoul
    restart: always